/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ListListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheListList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheListList.onFilterBar().iCheckFilterField("Material");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheListList.onTable().iCheckColumns(undefined, {"Product":{"header":"Material"},"ProductName":{"header":"Product Name"},"Component":{"header":"Component"},"ComponentName":{"header":"Component Name"},"ProductGroup":{"header":"Material Group"},"BOMItemQty":{"header":"Component Quantity"},"GrossWeight1":{"header":"Paper/Cardboard"},"GrossWeight2":{"header":"Foils/Containers/Foams"},"GrossWeight3":{"header":"Composite Materials"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheListList.onFilterBar().iExecuteSearch();
            
            Then.onTheListList.onTable().iCheckRows();

            When.onTheListList.onTable().iPressRow(0);
            Then.onTheListObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});