/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TP_ListObjectPageObjectPage journey");

        opaTest("Navigate to TP_ListObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTP_ListList.onFilterBar().iExecuteSearch();

            Then.onTheTP_ListList.onTable().iCheckRows();
            When.onTheTP_ListList.onTable().iPressRow(0);

            Then.onTheTP_ListObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTP_ListObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Product" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Component" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductGroup" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductName" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ComponentName" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BOMItemQty" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BOMItemQtyUnit" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BOMWeightUnit" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GrossWeight1" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GrossWeight2" });
            Then.onTheTP_ListObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GrossWeight3" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});