/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MMRListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMMRList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Product");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Plant");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Plant-Specific Material Status");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Product Type");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Procurement Type");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Sales Org.");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Dist. Channel");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Division");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Warehouse Number");
            Then.onTheMMRList.onFilterBar().iCheckFilterField("Product Group");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMMRList.onTable().iCheckColumns(12, {"Product":{"header":"Product"},"Plant":{"header":"Plant"},"ProfileCode":{"header":"Plant-Specific Material Status"},"ProductType":{"header":"Product Type"},"ProcurementType":{"header":"Procurement Type"},"ValuationClass":{"header":"Valuation Class"},"ProdWrhs1stLoadgEquipQuantity":{"header":"Loading Equipment Qty. 1"},"ProdWrhs2ndLoadgEquipQuantity":{"header":"Loading Equipment Qty. 2"},"ProductSalesOrg":{"header":"Sales Org."},"ProductDistributionChnl":{"header":"Dist. Channel"},"Division":{"header":"Division"},"ProductGroup":{"header":"Product Group"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheMMRList.onFilterBar().iExecuteSearch();
            
            Then.onTheMMRList.onTable().iCheckRows();

            When.onTheMMRList.onTable().iPressRow(0);
            Then.onTheMMRObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});